# Data Cleaning Notebook 5

Correction to error in column data type conversion.

In [2]:
import sys
sys.path.append('../')
import glob2 as glob
import json
import numpy as np
import pandas as pd

pd.options.display.max_columns = 200
pd.options.display.max_rows = 200
%matplotlib inline

import warnings; warnings.simplefilter('ignore')

In [3]:
pd.options.display.max_columns = 500
pd.options.display.max_rows = 500

In [4]:
# Importing Data
# path2data = '../Analysis/data/'

In [5]:
# Import Training and Test Data  
train_features = pd.read_csv('data2/dpc_train_features.csv', index_col='match_id')
train_targets = pd.read_csv('data2/dpc_train_target.csv', index_col='match_id')
test_features = pd.read_csv('data2/dpc_test_features.csv', index_col='match_id')
test_targets = pd.read_csv('data2/dpc_test_target.csv', index_col='match_id')

## Correction to 'is_pick' columns 

Shouldn't have converted to boolean because for a given index ranges, they will all read TRUE if selection step = hero pick and FALSE if selection step = hero ban

In [14]:
# Ban columns: [i]is_pick columns to replace with 0 
# 1-6, 11-14, 19-20
ban_cols = ['1is_pick', '2is_pick', '3is_pick', '4is_pick', '5is_pick', '6is_pick', '11is_pick', '12is_pick', '13is_pick', '14is_pick', '19is_pick', '20is_pick']

In [6]:
df1 = train_features
df2 = test_features

In [7]:
df1[['1is_pick', '2is_pick', '3is_pick', '4is_pick', '5is_pick', '6is_pick', '11is_pick', '12is_pick', '13is_pick', '14is_pick', '19is_pick', '20is_pick']] = 0
df2[['1is_pick', '2is_pick', '3is_pick', '4is_pick', '5is_pick', '6is_pick', '11is_pick', '12is_pick', '13is_pick', '14is_pick', '19is_pick', '20is_pick']] = 0

In [8]:
df1.head()

,1is_pick,1team,1hero_id,2is_pick,2team,2hero_id,3is_pick,3team,3hero_id,4is_pick,4team,4hero_id,5is_pick,5team,5hero_id,6is_pick,6team,6hero_id,7is_pick,7team,7hero_id,8is_pick,8team,8hero_id,9is_pick,9team,9hero_id,10is_pick,10team,10hero_id,11is_pick,11team,11hero_id,12is_pick,12team,12hero_id,13is_pick,13team,13hero_id,14is_pick,14team,14hero_id,15is_pick,15team,15hero_id,16is_pick,16team,16hero_id,17is_pick,17team,17hero_id,18is_pick,18team,18hero_id,19is_pick,19team,19hero_id,20is_pick,20team,20hero_id,21is_pick,21team,21hero_id,22is_pick,22team,22hero_id
match_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
5115031896,0,0,25,0,1,66,0,0,60,0,1,90,0,0,7,0,1,96,1,0,85,1,1,102,1,1,6,1,0,52,0,0,13,0,1,19,0,0,46,0,1,98,1,1,86,1,0,20,1,1,72,1,0,77,0,1,23,0,0,112,1,0,129,1,1,2
4865407245,0,1,71,0,0,18,0,1,55,0,0,66,0,1,129,0,0,96,1,1,37,1,0,121,1,0,103,1,1,100,0,1,106,0,0,104,0,1,16,0,0,76,1,0,65,1,1,8,1,0,46,1,1,57,0,0,114,0,1,10,1,1,17,1,0,42
4889341660,0,1,105,0,0,107,0,1,121,0,0,80,0,1,86,0,0,66,1,1,57,1,0,18,1,0,111,1,1,95,0,1,96,0,0,11,0,1,55,0,0,52,1,0,79,1,1,27,1,0,2,1,1,85,0,0,17,0,1,35,1,1,76,1,0,43
5050335216,0,0,84,0,1,90,0,0,19,0,1,79,0,0,60,0,1,23,1,0,103,1,1,96,1,1,86,1,0,106,0,0,61,0,1,10,0,0,93,0,1,41,1,1,37,1,0,9,1,1,72,1,0,76,0,1,16,0,0,39,1,0,108,1,1,59
4860032461,0,1,111,0,0,18,0,1,69,0,0,55,0,1,65,0,0,8,1,1,66,1,0,121,1,0,16,1,1,107,0,1,42,0,0,46,0,1,10,0,0,54,1,0,37,1,1,96,1,0,106,1,1,76,0,0,95,0,1,82,1,1,1,1,0,73

In [9]:
df2.head()

,1is_pick,1team,1hero_id,2is_pick,2team,2hero_id,3is_pick,3team,3hero_id,4is_pick,4team,4hero_id,5is_pick,5team,5hero_id,6is_pick,6team,6hero_id,7is_pick,7team,7hero_id,8is_pick,8team,8hero_id,9is_pick,9team,9hero_id,10is_pick,10team,10hero_id,11is_pick,11team,11hero_id,12is_pick,12team,12hero_id,13is_pick,13team,13hero_id,14is_pick,14team,14hero_id,15is_pick,15team,15hero_id,16is_pick,16team,16hero_id,17is_pick,17team,17hero_id,18is_pick,18team,18hero_id,19is_pick,19team,19hero_id,20is_pick,20team,20hero_id,21is_pick,21team,21hero_id,22is_pick,22team,22hero_id
match_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4870161807,0,1,66,0,0,97,0,1,91,0,0,71,0,1,111,0,0,55,1,1,121,1,0,18,1,0,37,1,1,65,0,1,57,0,0,106,0,1,76,0,0,93,1,0,88,1,1,10,1,0,104,1,1,69,0,0,114,0,1,17,1,1,79,1,0,52
5103391298,0,0,60,0,1,102,0,0,7,0,1,41,0,0,90,0,1,66,1,0,25,1,1,9,1,1,19,1,0,23,0,0,15,0,1,54,0,0,72,0,1,46,1,1,31,1,0,85,1,1,8,1,0,76,0,1,6,0,0,35,1,0,4,1,1,22
5062411190,0,0,9,0,1,66,0,0,52,0,1,60,0,0,97,0,1,23,1,0,25,1,1,5,1,1,41,1,0,120,0,0,74,0,1,72,0,0,86,0,1,113,1,1,101,1,0,111,1,1,16,1,0,100,0,1,1,0,0,34,1,0,81,1,1,49
4971396775,0,1,72,0,0,66,0,1,52,0,0,58,0,1,73,0,0,68,1,1,9,1,0,84,1,0,79,1,1,103,0,1,25,0,0,93,0,1,106,0,0,10,1,0,29,1,1,8,1,0,54,1,1,15,0,0,97,0,1,36,1,1,61,1,0,23
5059615080,0,1,97,0,0,41,0,1,9,0,0,102,0,1,66,0,0,85,1,1,23,1,0,57,1,0,121,1,1,104,0,1,98,0,0,43,0,1,76,0,0,101,1,0,5,1,1,30,1,0,93,1,1,72,0,0,91,0,1,106,1,1,90,1,0,54

In [74]:
df1.to_csv('dpc_train_features.csv')
df2.to_csv('dpc_test_features.csv')

Confirm correction

In [10]:
data1 = pd.read_csv('dpc_train_features.csv', index_col='match_id')
data2 = pd.read_csv('dpc_test_features.csv', index_col='match_id')

In [11]:
data1.shape, data2.shape

((1045, 66), (117, 66))

In [12]:
data1.head()

,1is_pick,1team,1hero_id,2is_pick,2team,2hero_id,3is_pick,3team,3hero_id,4is_pick,4team,4hero_id,5is_pick,5team,5hero_id,6is_pick,6team,6hero_id,7is_pick,7team,7hero_id,8is_pick,8team,8hero_id,9is_pick,9team,9hero_id,10is_pick,10team,10hero_id,11is_pick,11team,11hero_id,12is_pick,12team,12hero_id,13is_pick,13team,13hero_id,14is_pick,14team,14hero_id,15is_pick,15team,15hero_id,16is_pick,16team,16hero_id,17is_pick,17team,17hero_id,18is_pick,18team,18hero_id,19is_pick,19team,19hero_id,20is_pick,20team,20hero_id,21is_pick,21team,21hero_id,22is_pick,22team,22hero_id
match_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
5115031896,0,0,25,0,1,66,0,0,60,0,1,90,0,0,7,0,1,96,1,0,85,1,1,102,1,1,6,1,0,52,0,0,13,0,1,19,0,0,46,0,1,98,1,1,86,1,0,20,1,1,72,1,0,77,0,1,23,0,0,112,1,0,129,1,1,2
4865407245,0,1,71,0,0,18,0,1,55,0,0,66,0,1,129,0,0,96,1,1,37,1,0,121,1,0,103,1,1,100,0,1,106,0,0,104,0,1,16,0,0,76,1,0,65,1,1,8,1,0,46,1,1,57,0,0,114,0,1,10,1,1,17,1,0,42
4889341660,0,1,105,0,0,107,0,1,121,0,0,80,0,1,86,0,0,66,1,1,57,1,0,18,1,0,111,1,1,95,0,1,96,0,0,11,0,1,55,0,0,52,1,0,79,1,1,27,1,0,2,1,1,85,0,0,17,0,1,35,1,1,76,1,0,43
5050335216,0,0,84,0,1,90,0,0,19,0,1,79,0,0,60,0,1,23,1,0,103,1,1,96,1,1,86,1,0,106,0,0,61,0,1,10,0,0,93,0,1,41,1,1,37,1,0,9,1,1,72,1,0,76,0,1,16,0,0,39,1,0,108,1,1,59
4860032461,0,1,111,0,0,18,0,1,69,0,0,55,0,1,65,0,0,8,1,1,66,1,0,121,1,0,16,1,1,107,0,1,42,0,0,46,0,1,10,0,0,54,1,0,37,1,1,96,1,0,106,1,1,76,0,0,95,0,1,82,1,1,1,1,0,73

In [13]:
data2.head()

,1is_pick,1team,1hero_id,2is_pick,2team,2hero_id,3is_pick,3team,3hero_id,4is_pick,4team,4hero_id,5is_pick,5team,5hero_id,6is_pick,6team,6hero_id,7is_pick,7team,7hero_id,8is_pick,8team,8hero_id,9is_pick,9team,9hero_id,10is_pick,10team,10hero_id,11is_pick,11team,11hero_id,12is_pick,12team,12hero_id,13is_pick,13team,13hero_id,14is_pick,14team,14hero_id,15is_pick,15team,15hero_id,16is_pick,16team,16hero_id,17is_pick,17team,17hero_id,18is_pick,18team,18hero_id,19is_pick,19team,19hero_id,20is_pick,20team,20hero_id,21is_pick,21team,21hero_id,22is_pick,22team,22hero_id
match_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4870161807,0,1,66,0,0,97,0,1,91,0,0,71,0,1,111,0,0,55,1,1,121,1,0,18,1,0,37,1,1,65,0,1,57,0,0,106,0,1,76,0,0,93,1,0,88,1,1,10,1,0,104,1,1,69,0,0,114,0,1,17,1,1,79,1,0,52
5103391298,0,0,60,0,1,102,0,0,7,0,1,41,0,0,90,0,1,66,1,0,25,1,1,9,1,1,19,1,0,23,0,0,15,0,1,54,0,0,72,0,1,46,1,1,31,1,0,85,1,1,8,1,0,76,0,1,6,0,0,35,1,0,4,1,1,22
5062411190,0,0,9,0,1,66,0,0,52,0,1,60,0,0,97,0,1,23,1,0,25,1,1,5,1,1,41,1,0,120,0,0,74,0,1,72,0,0,86,0,1,113,1,1,101,1,0,111,1,1,16,1,0,100,0,1,1,0,0,34,1,0,81,1,1,49
4971396775,0,1,72,0,0,66,0,1,52,0,0,58,0,1,73,0,0,68,1,1,9,1,0,84,1,0,79,1,1,103,0,1,25,0,0,93,0,1,106,0,0,10,1,0,29,1,1,8,1,0,54,1,1,15,0,0,97,0,1,36,1,1,61,1,0,23
5059615080,0,1,97,0,0,41,0,1,9,0,0,102,0,1,66,0,0,85,1,1,23,1,0,57,1,0,121,1,1,104,0,1,98,0,0,43,0,1,76,0,0,101,1,0,5,1,1,30,1,0,93,1,1,72,0,0,91,0,1,106,1,1,90,1,0,54